import { Warga, MutasiRecord, TransaksiKas } from '../types';

/**
 * Menghasilkan kumpulan data warga dummy realistis untuk keperluan testing dan benchmarking UI.
 */
export function generateDummyWarga(): Warga[] {
  const timestamp = Date.now();
  const sampleData: Omit<Warga, 'id'>[] = [
    {
      nik: '3374101205800001',
      noKk: '3374100101800001',
      nama: 'Bambang Sudarmono, S.T.',
      tempatLahir: 'Semarang',
      tanggalLahir: '1980-05-12',
      jenisKelamin: 'L',
      agama: 'Islam',
      pendidikan: 'S1',
      pekerjaan: 'Karyawan Swasta',
      statusPerkawinan: 'Kawin',
      hubunganKeluarga: 'KEPALA KELUARGA',
      alamat: 'Jl. Gasem Raya Indah No. 12',
      rt: '02',
      rw: '04',
      statusKependudukan: 'Tetap',
      statusKehidupan: 'Hidup',
      tanggalDaftar: '2024-01-15',
      noHp: '081234567890',
    },
    {
      nik: '3374105408820002',
      noKk: '3374100101800001',
      nama: 'Hj. Endang Sri Lestari, S.Pd.',
      tempatLahir: 'Kudus',
      tanggalLahir: '1982-08-14',
      jenisKelamin: 'P',
      agama: 'Islam',
      pendidikan: 'S1',
      pekerjaan: 'Guru',
      statusPerkawinan: 'Kawin',
      hubunganKeluarga: 'ISTRI',
      alamat: 'Jl. Gasem Raya Indah No. 12',
      rt: '02',
      rw: '04',
      statusKependudukan: 'Tetap',
      statusKehidupan: 'Hidup',
      tanggalDaftar: '2024-01-15',
      noHp: '081398765432',
    },
    {
      nik: '3374101503100003',
      noKk: '3374100101800001',
      nama: 'Muhammad Rizky Pratama',
      tempatLahir: 'Semarang',
      tanggalLahir: '2010-03-15',
      jenisKelamin: 'L',
      agama: 'Islam',
      pendidikan: 'SMP',
      pekerjaan: 'Pelajar/Mahasiswa',
      statusPerkawinan: 'Belum Kawin',
      hubunganKeluarga: 'ANAK',
      alamat: 'Jl. Gasem Raya Indah No. 12',
      rt: '02',
      rw: '04',
      statusKependudukan: 'Tetap',
      statusKehidupan: 'Hidup',
      tanggalDaftar: '2024-01-15',
    },
    {
      nik: '3374101101750004',
      noKk: '3374100101750002',
      nama: 'Dr. Hendra Gunawan, Sp.PD.',
      tempatLahir: 'Solo',
      tanggalLahir: '1975-01-11',
      jenisKelamin: 'L',
      agama: 'Kristen',
      pendidikan: 'S2',
      pekerjaan: 'Dokter',
      statusPerkawinan: 'Kawin',
      hubunganKeluarga: 'KEPALA KELUARGA',
      alamat: 'Jl. Gasem Raya Kav. 18',
      rt: '02',
      rw: '04',
      statusKependudukan: 'Tetap',
      statusKehidupan: 'Hidup',
      tanggalDaftar: '2024-02-01',
      noHp: '081223344556',
    },
    {
      nik: '3374105206770005',
      noKk: '3374100101750002',
      nama: 'dr. Sylvia Anggraini',
      tempatLahir: 'Yogyakarta',
      tanggalLahir: '1977-06-12',
      jenisKelamin: 'P',
      agama: 'Kristen',
      pendidikan: 'S1',
      pekerjaan: 'Dokter',
      statusPerkawinan: 'Kawin',
      hubunganKeluarga: 'ISTRI',
      alamat: 'Jl. Gasem Raya Kav. 18',
      rt: '02',
      rw: '04',
      statusKependudukan: 'Tetap',
      statusKehidupan: 'Hidup',
      tanggalDaftar: '2024-02-01',
      noHp: '081233445566',
    },
    {
      nik: '3374102009650006',
      noKk: '3374100101650003',
      nama: 'H. Ahmad Syukron, M.Ag.',
      tempatLahir: 'Demak',
      tanggalLahir: '1965-09-20',
      jenisKelamin: 'L',
      agama: 'Islam',
      pendidikan: 'S2',
      pekerjaan: 'PNS/Dosen',
      statusPerkawinan: 'Kawin',
      hubunganKeluarga: 'KEPALA KELUARGA',
      alamat: 'Jl. Gasem Raya Indah No. 24',
      rt: '02',
      rw: '04',
      statusKependudukan: 'Tetap',
      statusKehidupan: 'Hidup',
      tanggalDaftar: '2024-02-10',
      noHp: '081555666777',
    },
    {
      nik: '3374106511680007',
      noKk: '3374100101650003',
      nama: 'Hj. Nur Hidayati',
      tempatLahir: 'Kendal',
      tanggalLahir: '1968-11-25',
      jenisKelamin: 'P',
      agama: 'Islam',
      pendidikan: 'SMA',
      pekerjaan: 'Mengurus Rumah Tangga',
      statusPerkawinan: 'Kawin',
      hubunganKeluarga: 'ISTRI',
      alamat: 'Jl. Gasem Raya Indah No. 24',
      rt: '02',
      rw: '04',
      statusKependudukan: 'Tetap',
      statusKehidupan: 'Hidup',
      tanggalDaftar: '2024-02-10',
    },
    {
      nik: '3374100504000008',
      noKk: '3374100101650003',
      nama: 'Aisyah Rahmawati, S.Kom.',
      tempatLahir: 'Semarang',
      tanggalLahir: '2000-04-05',
      jenisKelamin: 'P',
      agama: 'Islam',
      pendidikan: 'S1',
      pekerjaan: 'Software Engineer',
      statusPerkawinan: 'Belum Kawin',
      hubunganKeluarga: 'ANAK',
      alamat: 'Jl. Gasem Raya Indah No. 24',
      rt: '02',
      rw: '04',
      statusKependudukan: 'Tetap',
      statusKehidupan: 'Hidup',
      tanggalDaftar: '2024-02-10',
      noHp: '081288990011',
    },
  ];

  return sampleData.map((item, idx) => ({
    ...item,
    id: `dummy-w-${timestamp}-${idx}`,
  }));
}

/**
 * Menghasilkan transaksi kas dummy realistis
 */
export function generateDummyKas(): TransaksiKas[] {
  const timestamp = Date.now();
  return [
    {
      id: `dummy-k-${timestamp}-1`,
      tanggal: new Date().toISOString().split('T')[0],
      keterangan: 'Iuran Wajib Bulanan RT (Warga Blok A & B)',
      kategori: 'Iuran Warga',
      jenis: 'PEMASUKAN',
      nominal: 1250000,
    },
    {
      id: `dummy-k-${timestamp}-2`,
      tanggal: new Date().toISOString().split('T')[0],
      keterangan: 'Honor & Insentif Petugas Keamanan / Satpam Pos',
      kategori: 'Keamanan & Ronda',
      jenis: 'PENGELUARAN',
      nominal: 800000,
    },
    {
      id: `dummy-k-${timestamp}-3`,
      tanggal: new Date().toISOString().split('T')[0],
      keterangan: 'Peremajaan Lampu Sorot LED Lapangan & Pos Kamling',
      kategori: 'Sarana & Prasarana',
      jenis: 'PENGELUARAN',
      nominal: 350000,
    },
    {
      id: `dummy-k-${timestamp}-4`,
      tanggal: new Date().toISOString().split('T')[0],
      keterangan: 'Dana Sosial Warga Sakit (Keluarga Bpk. Bambang)',
      kategori: 'Sosial & Kematian',
      jenis: 'PENGELUARAN',
      nominal: 250000,
    },
    {
      id: `dummy-k-${timestamp}-5`,
      tanggal: new Date().toISOString().split('T')[0],
      keterangan: 'Donasi Pembangunan Gapura RT dari Warga Donatur',
      kategori: 'Donasi / Sumbangan',
      jenis: 'PEMASUKAN',
      nominal: 2000000,
    },
  ];
}

/**
 * Menghasilkan data mutasi dummy realistis
 */
export function generateDummyMutasi(wargaList: Warga[]): MutasiRecord[] {
  const timestamp = Date.now();
  const targetWarga = wargaList[0] || {
    id: 'dummy-w-0',
    nama: 'Bambang Sudarmono',
    nik: '3374101205800001',
    noKk: '3374100101800001',
    jenisKelamin: 'L',
  };

  return [
    {
      id: `dummy-m-${timestamp}-1`,
      wargaId: targetWarga.id,
      nama: targetWarga.nama,
      nik: targetWarga.nik,
      noKk: targetWarga.noKk,
      jenisKelamin: targetWarga.jenisKelamin,
      jenisMutasi: 'Pindah_Masuk',
      tanggal: new Date().toISOString().split('T')[0],
      keterangan: 'Pindah domisili resmi dari Boyolali ke RT 02 / RW 04',
    },
  ];
}
